all:
	clang -Wall -dynamiclib -o ig_video_media_patch_avc_wa_oob_write.dylib ig_video_media_patch_avc_wa_oob_write.c -framework IOKit -arch i386 -arch x86_64 
	clang -Wall -dynamiclib -o ig_video_media_avc_decode_oob_read.dylib ig_video_media_avc_decode_oob_read.c -framework IOKit -arch i386 -arch x86_64 
	clang -Wall -dynamiclib -o ig_video_media_avc_decode_oob_write.dylib ig_video_media_avc_decode_oob_write.c -framework IOKit -arch i386 -arch x86_64 
	clang -Wall -dynamiclib -o ig_video_media_avcpak_oob_write.dylib ig_video_media_avcpak_oob_write.c -framework IOKit -arch i386 -arch x86_64 
	clang -Wall -dynamiclib -o ig_video_media_avcpak_oob_write_2.dylib ig_video_media_avcpak_oob_write_2.c -framework IOKit -arch i386 -arch x86_64 

